openapi: 3.0.0
info:
  title: A bot for collecting feedback and monitoring service levels API
  version: 0.0.1
servers:
  - url: http://localhost:8000/api/v1/
    description: Dev server
paths:
  /keyboard/create:
    post:
      summary: Метод отправки клавиатуры
      tags:
        - API's модуля (Модуль вызывает api коннектора)
      operationId: sendKeyboard
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/KeyboardRequest"
      responses:
        '200':
          description: Успешный ответ с отправленной клавиатурой
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/KeyboardResponse"
        'default':
          description: Все нестандартное
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Error"
  /keyboard/update:
    post:
      summary: Метод обновления клавиатуры
      tags:
        - API's модуля (Модуль вызывает api коннектора)
      operationId: updateKeyboard
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/KeyboardRequestUpdate"
      responses:
        '200':
          description: Успешный ответ обновления клавиатуры
        'default':
          description: Все нестандартное
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Error"
  /message:
    post:
      summary: Метод отправки сообщения
      tags:
        - API's модуля (Модуль вызывает api коннектора)
      operationId: sendMessage
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Message"
      responses:
        '200':
          description: Успешный ответ с отправленной кнопкой клавиатуры
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/SendPlaceInfoRequestWithMessage"
        'default':
          description: Все нестандартное
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Error"
  /keyboard/input:
    post:
      summary: Метод отправки выбранной кнопки
      tags:
        - API's коннектора (Коннектор вызывает api модуля)
      operationId: enterKeyboard
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EnterKeyboard"
      responses:
        '200':
          description: Успешный ответ с отправленной кнопкой клавиатуры
        'default':
          description: Все нестандартное
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Error"
  /image:
    post:
      summary: Метод отправки изображений
      tags:
        - API's коннектора (Коннектор вызывает api модуля)
      operationId: sendImages
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Image"
      responses:
        '200':
          description: Успешный ответ с urls изображений
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/ImageURL"
        'default':
          description: Все нестандартное
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Error"
  /command:
    post:
      summary: Метод отправки команды
      tags:
        - API's коннектора (Коннектор вызывает api модуля)
      operationId: sendCommand
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Command"
      responses:
        '200':
          description: Успешный ответ отправленной команды
        'default':
          description: Все нестандартное
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Error"
  /user_message:
    post:
      summary: Метод отправки сообщения от пользователя
      tags:
        - API's коннектора (Коннектор вызывает api модуля)
      operationId: sendMessageFromModule
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Message"
      responses:
        '200':
          description: Успешный ответ отправленного сообщения
        'default':
          description: Все нестандартное
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Error"  
  /message/action:
    post:
      summary: Метод отправки действия над сообщением
      tags:
        - API's коннектора (Коннектор вызывает api модуля)
      operationId: sendActionOnMessage
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ActionOnMessage"
      responses:
        '200':
          description: Успешный ответ отправки действия над сообщением
        'default':
          description: Все нестандартное
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Error"


  /appeal-agent:
    post:
      tags: 
        - API's модуля агента
      summary: Отправить обращение агенту
      operationId: startAppealProcessing
      description: Запускает выполнение workflow. Возвращает результат обработки обращения агентом.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AgentRequest'
      responses:
        '200':
          description: Workflow выполнен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AgentResponse'                
  
    
            
            
components:
  schemas:
    KeyboardRequest:
      type: object
      required:
        - user_id
        - title
        - buttons
        - place_info
      properties:
        user_id:
          type: string
          example: 123
        place:
          $ref: "#/components/schemas/SendPlaceInfoRequest"
        title:
          type: string
          example: "Выбор подразделения"
        buttons:
          type: array
          items: 
            $ref: "#/components/schemas/Button"
          example: 
            - text: "СТО Димитровский мост"
            - text: "СТО ДОК"
    KeyboardResponse:
      type: object
      required:
        - user_id
        - place
        - date_time
      properties:
        user_id:
          type: string
          example: 123
        place:
          $ref: "#/components/schemas/SendPlaceInfoResponse"
        date_time:
              type: string
              format: date-time
              example: "2025-01-29T15:00:00+01:00"
        
    KeyboardRequestUpdate:
      type: object
      required:
        - user_id
        - title
        - buttons
        - place
      properties:
        user_id:
          type: string
          example: 123
        place:
          $ref: "#/components/schemas/SendPlaceInfoRequestWithMessage"
        title:
          type: string
          example: "Выбор подразделения"
        buttons:
          type: array
          items: 
            $ref: "#/components/schemas/Button"
          example: 
            - text: "СТО Димитровский мост"
            - text: "СТО ДОК"
        
    Button:
      type: object
      required: 
        - text
      properties:
        text:
          type: string
    EnterButtonKeyboard:
      type: object
      properties:
        send_place_info:
          $ref: "#/components/schemas/SendPlaceInfoResponse"
        button:
          $ref: "#/components/schemas/Button"
    SendPlaceInfoRequest:
      type: object
      required: 
        - chat_id
      properties:
        chat_id:
          type: string
          example: 123

    SendPlaceInfoRequestWithMessage:
      type: object
      required: 
        - user_id
        - date_time
        - place
      properties:
        user_id:
            type: string
            example: 123
        place:
          $ref: "#/components/schemas/SendPlaceInfoResponse"
        date_time:
            type: string
            format: date-time
            example: "2025-01-29T15:00:00+01:00"

    SendPlaceInfoResponse:
      type: object
      required: 
        - chat_id
        - message_id
      properties:
        chat_id:
          type: string
          example: 123
        message_id:
          type: string
          example: 123
    Message:
      type: object
      required: 
        - user_id
        - place
        - text
        - date_time
      properties:
        user_id:
          type: string
          example: 123
        place:
          $ref: "#/components/schemas/SendPlaceInfoRequest"
        text:
          type: string
        date_time:
            type: string
            format: date-time
            example: "2025-01-29T15:00:00+01:00"
        
    EnterKeyboard:
      type: object
      required:
        - user_id
        - button
        - place
        - date_time
      properties:
        user_id:
          type: string
          example: 123
        button:
          type: string
          example: "СТО Димитровский мост"
        place:
          $ref: "#/components/schemas/SendPlaceInfoResponse"
        date_time:
            type: string
            format: date-time
            example: "2025-01-29T15:00:00+01:00"
    Image:
      type: object
      required: 
        - attachments_base64
      properties:
        user_id:
          type: string
          example: 123
        place:
          $ref: "#/components/schemas/SendPlaceInfoRequest"
        attachments_base64:
          type: array
          items:
            type: string
            format: byte
            description: Массив изображений в Base64
        date_time:
            type: string
            format: date-time
            example: "2025-01-29T15:00:00+01:00"
    ImageURL:
      type: object
      properties:
        attachment_urls:
          type: array
          items:
            type: string
            format: uri
            example: "https://storage.example.com/images/1.jpg"
    Command:
      type: object
      required: 
        - user_id
        - place
        - name
        - date_time
      properties:
        user_id:
          type: string
          example: 123
        place:
          $ref: "#/components/schemas/SendPlaceInfoRequest"
        name:
          type: string
          example: start
          description: Текст команды
        date_time:
          type: string
          format: date-time
          example: "2025-01-29T15:00:00+01:00"

    ActionOnMessage:
      type: object
      required: 
        - user_id
        - place
        - action
        - date_time
      properties:
        user_id:
          type: string
          example: 123
        place:
          $ref: "#/components/schemas/SendPlaceInfoRequest"
        action:
          type: string
          example: read
        date_time:
          type: string
          format: date-time
          example: "2025-01-29T15:00:00+01:00"


      
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
        message:
          type: string

    ExecutionResponse:
      type: object
      properties:
        executionId:
          type: string
          example: "dfq0jc2purufolepkm26-864c04cf-19c6-4b7b-8a0c-da1b846af955"
    

    
    AgentResponse:
          type: object
          properties:
            result:
              type: object
              example: "{\"Описание проблемы:\\nККМ не печатает чеки\\n\\nКлассификация:\\nКатегория: ТехПоддержка\\nПО: ККМ\\nКритичность: проблема\\nЭскалация: true\"}"

            escalate:
              type: boolean
              example: true 

            previous_response_id:
              type: string
              example: "d456a879-93ba-4e28-ae71-875cfe70585e"

            chatId:
              type: integer
              example: 12321  
        
    AgentRequest:
      type: object
      required:
        - message
        - chatId
      properties:
        message:
          type: string
          example: "У меня проблема с ККМ"
        
        escalate:
          type: boolean
          example: false
        
        chatId:
          type: integer
          example: 12321

        category:
          type: string
          example: "ТехПоддержка"
        
        software:
          type: string
          example: "ККМ"
        
        criticality:
          type: string
          example: "проблема"
        
        image:
          type: array
          items:
            type: string
          example: "iVBORw0KGgoAAAANSUhEUgAAAMIAAAAeCAYAAAB+HcFlAAAA4WlDQ1BzUkdCAAAYlWNgYDzNAARMDgwMuXklRUHuTgoRkVEKDEggMbm4gAE3YGRg+HYNRDIwXNYNLGHlx6MWG+AsAloIpD8AsUg6mM3IAmInQdgSIHZ5SUEJkK0DYicXFIHYQBcz8BSFBDkD2T5AtkI6EjsJiZ2SWpwMZOcA2fEIv+XPZ2Cw+MLAwDwRIZY0jYFhezsDg8QdhJjKQgYG/lYGhm2XEWKf/cH+ZRQ7VJJaUQIS8dN3ZChILEoESzODAjQtjYHh03IGBt5IBgbhCwwMXNEQd4ABazEwoEkMJ0IAAHLYNoSjH0ezAAAACXBIWXMAAA7DAAAOwwHHb6hkAAAGn0lEQVR4nO2bT2gTWRjAf8pediBrllCQ8dAIKqQ9rNB68DL1spBQWTyFUigpMVCQnB107y3JWQqFtiSElRJYELEkR52Lh7WgB1vQQtODg1AC2Q3MLnvQPcxMMv+STLQ11X2/U+bfe9+f9733fW8mZ1LXfv6IQPA/5Pdff+v8PjtCOQSCU4MIBIEAEQgCASACQSAARCAIBIAIBIEA+CoDIUuhWmJNTY5akFOAsMVx8d2oBQhDrlhiJm4f6TxLL7I+QnlGibDFyXDqAyFXLDET2+NhukBt1MKMGGGLk+N0p0aKyrW4wW5ZOF7Y4mQ51YGQuj6O1D7kpTZqSUaPsMXJMnRqVKmWgi80NBbubprLNxoLT8ZYyyeQ7OvtPR7e9s5mWQpVBblzrPMsfb+T816ISdA8AnWVypTUfczqC4DMMpXZKLsP7rDiGSSdVMLuV1F7yOSVw4lTpiT3NuaYiPj17sribcWtUzD+/o2dLZYK9c5xKFsAKXWV+SuHPlun1FXmp1o+WczzjvZ88vawTaA/A+zju6+/z0PLr6is5cdpePxu66NvL6KWe+tp7Gy5JB86EBbSi8GCOYlNs5Y55FF60VLGVH5+QwXPoGRniwXL4bliiZnqMqTvs06SsRgQUbjV3GIhbQ0KRWUtr1ApYg6A8j76rEL8ehK07sAxUwnQt63+rEGqby+yVAbbabZManrT0X6ClseQHQe2nTl6lkLRuuxo337OtNEAg1rPGQ47mDLMUSnK1iAPaYuhsAetzrP0nY4PTR+sMuYZYO6BZdmumKXm6lcmGuneaw5qx+WBPv9MFJVbrqB26BR36GnZ9++/PvD9gZkUnUxqFGnxhyuiN1Ef7GFEEtzIWMLdTCC193jkmPXW72royFxTk9hGpaG5Zka0AkvbOsSnuaeYbT/dMZCmFHIOEVLXx5HQeWsPekWGhuZwZp2VslumfuSKVhB49bIGQup8FDr9hcWUyzv7+3UMa4shyChWELgH4PrdLXbbEhM3s30ernPUBGJjpJynlTGiGLQOgp8a7PPPIcm9TAKpoaO7ZLInRIeeWoFHOwYff/jAv9apkwmExr4/urUjWkD0fBLIcjkOuuZdWnVabZBi3YXTaLrUMinvoyOZqwBQe36IgczlzoBOcvWKhLGjWTPAT8QjBrtPPLOmS6Z+mPIab171LFRr71vgkiEEllyN53X/NY+OEM4WYclNysF+os7LNwbEL7kmFjeD7dHrmTA+/xRS6i9mYN/dd5+/Po7U3uOpZ4Iy/fWRjz+ax6PZPlXGiALSbInKbMD1JtgGigY24LmmvaKRSTAxmQU2/QPs4jkkJCbyJSp5f2tGSHlb7wMGrE35PgsHKmt5r06t3s9cPId/IQ9iCFsARBLMV0vM++61ZbFSrWaozgGQPb7qppgOLp5DosVRUEEfyudh5feQWbbqgjusk6XguHQhJvVpr8sXD4TW+zpoMq3APNzNUXOOicCZwkoVOtRZ0RQqs+Ys9s67w3LwJwZRX2EVGu2IVj4R+nZXjtyvRrDkGkx9CFsQWMi6ZTHbGwZv8ZkrlqhsuPsxVxktONe3bDjI5+Hkd5KlMOtNe7u8axoQ8xff8CX+mBO0rGYuIXfyR3MWkyf75aGw/lrv25YrpSjvoyNzOZPlxpTkXoK1I1qfkD50CSOvnaMGOySQfnJ5dBzKFiF41+yV/phpZXDa1GX9tQ6Rca52ahMr9Xndq2gP5/NhiWcUZHSe9dgsqL1veeQM5oTeI8jMFB0KKyprszI0Xlgzcp0VTYe44vtOJldc7jqnrLHblpnZULtFma8tm03eNkBWpon6ila7oJ6j4Mrhk9wrqu6CLxCrsI4rVJx6kaVgH2cUJiL9BkIQm6jbOtLUnNsOlo7GzuOujkPZYjC1wmOzveqyKxhyRWsnacAuVG5SBseqm1KnkftuFoT0+VBISBFPIeylrJnFf97Th6Lyz8UPncOTSY0aGg+b01Sq3TB0bQ+CI6eeo1Kdc9231Dmqs3K7Tq5YcuV4vrYs1p/scS2fQGq88BmmVrhDLbNMJSDXDVXwaQWWNHML1amXvr1IZ3kOKMoG0sMO3lRkWFsMptveTLXEjH26HfwJh7dGMPf/ne9gDHYfDNgCDeXzIRm4AvfQE52zr7rrwJnj/vN+54Xa0Pvax0CPlywCQRDf7J/3zX1q8RmCYHi+nUCwX5z49qkFgsGc+s+wB+L4fsifVwsE4Tj2GkEg+Fr4ZmsEgeBTEYEgECBSI4EAECuCQADAf6HbubpdHCA6AAAAAElFTkSuQmCC"
        
        previous_response_id:
          type: string
          example: "d456a879-93ba-4e28-ae71-875cfe70585e"